"""Relevancy gates — two quality checks that run before and after LLM generation.

WHY GATES?
  Without gates, the LLM gets called even when:
  - No relevant chunks were found (wastes tokens, produces hallucinated answer)
  - The answer it gave is unrelated to the question (user gets misleading response)

GATE 1 — Retrieval Relevancy Gate (before LLM):
  Check if the top Qdrant result score crosses a minimum threshold.
  If every retrieved chunk is below the threshold → we have nothing useful to say.
  Action: skip LLM call entirely, return escalation immediately.

GATE 2 — Answer Relevancy Check (after LLM):
  Ask a cheap lightweight LLM: "Does this answer actually address the question?"
  If the answer is off-topic (e.g., LLM hallucinated or deflected) → escalate.
  Uses Gemini/Groq so it costs almost nothing.
"""

from app.llm import lightweight
from app.helpers.logger import get_logger

logger = get_logger(__name__)

# Minimum retrieval score to proceed to LLM generation.
# Below this = Qdrant found nothing semantically relevant.
_MIN_RETRIEVAL_SCORE = 0.35

_RELEVANCY_CHECK_PROMPT = """You are a strict relevancy judge for a customer support chatbot.

Customer question: {query}

Answer given: {answer}

Does the answer directly address the customer's question?
Reply with ONLY one word: "yes" or "no".
""".strip()


def retrieval_gate(results: list, has_direct_data: bool = False) -> bool:
    """
    GATE 1: Check if retrieved FAQ chunks are relevant enough to use.

    Args:
        results:         Qdrant search results (list of ScoredPoints).
        has_direct_data: True when invoice or order JSON was loaded.
                         Direct data bypasses this gate — invoice is always relevant.

    Returns:
        True  → pass (proceed to LLM generation)
        False → block (no relevant context found, escalate immediately)
    """
    # Invoice/order data always passes — it's direct user data, not retrieved
    if has_direct_data:
        logger.debug("GATE1 PASS: direct data present (invoice/orders) — skipping score check")
        return True

    if not results:
        logger.info("GATE1 BLOCK: no results returned from Qdrant")
        return False

    top_score = results[0].score
    passed = top_score >= _MIN_RETRIEVAL_SCORE

    if passed:
        logger.debug("GATE1 PASS: top_score=%.3f >= threshold=%.2f", top_score, _MIN_RETRIEVAL_SCORE)
    else:
        logger.info(
            "GATE1 BLOCK: top_score=%.3f < threshold=%.2f — nothing relevant in knowledge base",
            top_score, _MIN_RETRIEVAL_SCORE,
        )
    return passed


def answer_relevancy_gate(query: str, answer: str) -> bool:
    """
    GATE 2: Ask a lightweight LLM if the generated answer actually addresses the query.

    Uses Gemini (primary) or Groq (fallback). If both are unavailable, defaults to
    True (pass) so the pipeline degrades gracefully rather than blocking all answers.

    Args:
        query:  The user's question.
        answer: The answer generated by the main LLM (Azure OpenAI).

    Returns:
        True  → pass (answer is on-topic)
        False → block (answer is off-topic / evasive, should escalate)
    """
    prompt = _RELEVANCY_CHECK_PROMPT.format(query=query, answer=answer[:500])
    verdict = lightweight.call(prompt, max_tokens=5).lower()

    if not verdict:
        # Lightweight LLM unavailable — let the answer through
        logger.warning("GATE2 SKIP: lightweight LLM unavailable — defaulting to pass")
        return True

    passed = verdict.startswith("yes")
    logger.info("GATE2 %s: answer_relevancy verdict=%r", "PASS" if passed else "BLOCK", verdict)
    return passed
